[build]
builder = "nixpacks"

[build.nixpacks]
pythonVersion = "3.11"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"